/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package snake1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        int bodyx[] = {1, 2, 3};
        int bodyy[] = {1, 2, 3};
        int[] newArrayx = new int[bodyx.length];
        int[] newArrayy = new int[bodyx.length];
        newArrayx[0] = 0;
        newArrayy[0] = 0;
        System.arraycopy(bodyx, 0, newArrayx, 1, bodyx.length - 1);
        System.arraycopy(bodyy, 0, newArrayy, 1, bodyy.length - 1);
        bodyx = newArrayx;
        bodyy = newArrayy;
        for (int i : bodyx) {
            System.out.println(i);
        }
        System.out.println(bodyx.length);
    }
}
